project:
  type: website

website:
  title: "DSCI_521_Lab2_Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


deploy:
  method: gh-pages



